# 立ち上げる
# docker-compose up --build

# container を落とすことにより、DB, Metadata を消去する
# docker-compose down

version: "3.6"
services:
  db:
    container_name: postgres
    image: postgres:13
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 20
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: hasura
      POSTGRES_PASSWORD: secret
      TZ: Asia/Tokyo
