output   = "my_models"
wipe     = true
no-tests = true
add-enum-types = true

[psql]
  dbname = "postgres"
  host   = "localhost"
  port   = 5432
  user   = "hasura"
  pass   = "secret"
  sslmode = "disable"
